[2023-06-08 14:17:08,174][whylogs.api.usage_stats][WARNING] - Connection error. Skip stats collection.
[2023-06-08 14:19:56,339][whylogs.api.writer.whylabs][INFO] - checking: https://whylabs-public.s3.us-west-2.amazonaws.com/whylogs_config/whylabs_condition_count_disabled
[2023-06-08 14:23:38,415][whylogs.api.writer.whylabs][WARNING] - Error trying to read whylabs config, falling back to defaults for uncompounding
[2023-06-08 14:23:40,274][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DDD7D1A220>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /daily-log-untrusted/2023-06-08/org-YNx5UG-model-3-2023-06-08T211934.06-wABCXz5bRdQe8otNIG4vlKZ6qKXOjx2U.bin?Expires=1686260321&Signature=C-V~ybMa8PbHQ3XvAHHPpIu23SdgdpAu6fpbxA0V-690SI8VEofLlbn1MLFYKnBbTvH5rZorrnmMfaDfDLskStvPuqnyz6liI~89wvpDPXfAkj-1E8BcNgINacpYPvbN7KGEvJ2xOvFUMo~2wCQ8QmC9pKwrrdAy2l5Fgl3Js4CZ~ptGgCDL~30VeNGUW~iwCKGDG0raxsKvIrzedwkWkk-zDsxNUNfbAbsw4JlzyMUNBOZYxBTwaNJJw4KffBLu2QspDKzXBDIvhgVA0Sx7VPDUbsFzV1Lt8gwnBSYWIF6y27i7AX3T4HhRTWwy63J4~B1D5OK2OMHaTgIy2IJZCg__&Key-Pair-Id=K42ZLMP4PCXOG
[2023-06-08 14:23:40,281][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DDD7D1A370>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /daily-log-untrusted/2023-06-08/org-YNx5UG-model-3-2023-06-08T211934.06-wABCXz5bRdQe8otNIG4vlKZ6qKXOjx2U.bin?Expires=1686260321&Signature=C-V~ybMa8PbHQ3XvAHHPpIu23SdgdpAu6fpbxA0V-690SI8VEofLlbn1MLFYKnBbTvH5rZorrnmMfaDfDLskStvPuqnyz6liI~89wvpDPXfAkj-1E8BcNgINacpYPvbN7KGEvJ2xOvFUMo~2wCQ8QmC9pKwrrdAy2l5Fgl3Js4CZ~ptGgCDL~30VeNGUW~iwCKGDG0raxsKvIrzedwkWkk-zDsxNUNfbAbsw4JlzyMUNBOZYxBTwaNJJw4KffBLu2QspDKzXBDIvhgVA0Sx7VPDUbsFzV1Lt8gwnBSYWIF6y27i7AX3T4HhRTWwy63J4~B1D5OK2OMHaTgIy2IJZCg__&Key-Pair-Id=K42ZLMP4PCXOG
[2023-06-08 14:23:40,286][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DDD7D1A4C0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /daily-log-untrusted/2023-06-08/org-YNx5UG-model-3-2023-06-08T211934.06-wABCXz5bRdQe8otNIG4vlKZ6qKXOjx2U.bin?Expires=1686260321&Signature=C-V~ybMa8PbHQ3XvAHHPpIu23SdgdpAu6fpbxA0V-690SI8VEofLlbn1MLFYKnBbTvH5rZorrnmMfaDfDLskStvPuqnyz6liI~89wvpDPXfAkj-1E8BcNgINacpYPvbN7KGEvJ2xOvFUMo~2wCQ8QmC9pKwrrdAy2l5Fgl3Js4CZ~ptGgCDL~30VeNGUW~iwCKGDG0raxsKvIrzedwkWkk-zDsxNUNfbAbsw4JlzyMUNBOZYxBTwaNJJw4KffBLu2QspDKzXBDIvhgVA0Sx7VPDUbsFzV1Lt8gwnBSYWIF6y27i7AX3T4HhRTWwy63J4~B1D5OK2OMHaTgIy2IJZCg__&Key-Pair-Id=K42ZLMP4PCXOG
