[2023-06-08 12:59:15,937][whylogs.api.usage_stats][WARNING] - Connection error. Skip stats collection.
[2023-06-08 13:01:40,551][whylogs.api.writer.whylabs][INFO] - checking: https://whylabs-public.s3.us-west-2.amazonaws.com/whylogs_config/whylabs_condition_count_disabled
[2023-06-08 13:01:40,651][whylogs.api.writer.whylabs][WARNING] - Error trying to read whylabs config, falling back to defaults for uncompounding
[2023-06-08 13:01:40,795][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000251880D4640>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 13:01:40,797][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000251880D47C0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 13:01:40,800][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000251880D4940>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
