[2023-06-08 13:05:37,774][whylogs.api.writer.whylabs][INFO] - checking: https://whylabs-public.s3.us-west-2.amazonaws.com/whylogs_config/whylabs_condition_count_disabled
[2023-06-08 13:05:39,316][whylogs.api.writer.whylabs][WARNING] - Error trying to read whylabs config, falling back to defaults for uncompounding
[2023-06-08 13:05:44,486][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011A577FA370>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /daily-log-untrusted/2023-06-08/org-YNx5UG-model-3-2023-06-08T200515.561-d57Lf0zC0PVOhU9weLp2g6GVgo6OaUvn.bin?Expires=1686255644&Signature=qtzBnmDzDlla8C2WsW0aqHsvlxqsX9dLx-VgGQ7JLpW5HNedP0Wjgra0-nd7DuA3fWXPS5txJVNkvdLBeleZzJoc4AUuhXl0iz0FSYZUdgSjVVvrnQfz-EqZVO8q-aSrcrzKk8dAk~qKsWY3nKZWNnSuH6cDXIM-nUo4cidfksEQNDrUM5cvcF3Lw5vBghPtRY3z6Qsr5apFtoj4UvwtUey4GXz~fXh0TiLBDMlA6fv5ty3GGvTJQS9nrCIEBnzml545wi6MSyKWVagbP9XENhTmk25FSSBROPHq1Nv-jqoBht90ucoG5qai5D7f8d~TDqAkvNqRE1dwFy4uNyiRQA__&Key-Pair-Id=K42ZLMP4PCXOG
[2023-06-08 13:05:44,497][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011A577FA4C0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /daily-log-untrusted/2023-06-08/org-YNx5UG-model-3-2023-06-08T200515.561-d57Lf0zC0PVOhU9weLp2g6GVgo6OaUvn.bin?Expires=1686255644&Signature=qtzBnmDzDlla8C2WsW0aqHsvlxqsX9dLx-VgGQ7JLpW5HNedP0Wjgra0-nd7DuA3fWXPS5txJVNkvdLBeleZzJoc4AUuhXl0iz0FSYZUdgSjVVvrnQfz-EqZVO8q-aSrcrzKk8dAk~qKsWY3nKZWNnSuH6cDXIM-nUo4cidfksEQNDrUM5cvcF3Lw5vBghPtRY3z6Qsr5apFtoj4UvwtUey4GXz~fXh0TiLBDMlA6fv5ty3GGvTJQS9nrCIEBnzml545wi6MSyKWVagbP9XENhTmk25FSSBROPHq1Nv-jqoBht90ucoG5qai5D7f8d~TDqAkvNqRE1dwFy4uNyiRQA__&Key-Pair-Id=K42ZLMP4PCXOG
[2023-06-08 13:05:44,500][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011A577FA610>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /daily-log-untrusted/2023-06-08/org-YNx5UG-model-3-2023-06-08T200515.561-d57Lf0zC0PVOhU9weLp2g6GVgo6OaUvn.bin?Expires=1686255644&Signature=qtzBnmDzDlla8C2WsW0aqHsvlxqsX9dLx-VgGQ7JLpW5HNedP0Wjgra0-nd7DuA3fWXPS5txJVNkvdLBeleZzJoc4AUuhXl0iz0FSYZUdgSjVVvrnQfz-EqZVO8q-aSrcrzKk8dAk~qKsWY3nKZWNnSuH6cDXIM-nUo4cidfksEQNDrUM5cvcF3Lw5vBghPtRY3z6Qsr5apFtoj4UvwtUey4GXz~fXh0TiLBDMlA6fv5ty3GGvTJQS9nrCIEBnzml545wi6MSyKWVagbP9XENhTmk25FSSBROPHq1Nv-jqoBht90ucoG5qai5D7f8d~TDqAkvNqRE1dwFy4uNyiRQA__&Key-Pair-Id=K42ZLMP4PCXOG
