[2023-06-08 16:01:47,593][whylogs.api.usage_stats][WARNING] - Connection error. Skip stats collection.
[2023-06-08 16:07:35,955][whylogs.api.writer.whylabs][INFO] - checking: https://whylabs-public.s3.us-west-2.amazonaws.com/whylogs_config/whylabs_condition_count_disabled
[2023-06-08 16:07:36,031][whylogs.api.writer.whylabs][WARNING] - Error trying to read whylabs config, falling back to defaults for uncompounding
[2023-06-08 16:07:36,138][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020CF5C387F0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 16:07:36,140][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020CF5C38970>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 16:07:36,142][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020CF5C38AF0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
