[2023-06-08 15:53:15,003][whylogs.api.writer.whylabs][INFO] - checking: https://whylabs-public.s3.us-west-2.amazonaws.com/whylogs_config/whylabs_condition_count_disabled
[2023-06-08 15:53:15,085][whylogs.api.writer.whylabs][WARNING] - Error trying to read whylabs config, falling back to defaults for uncompounding
[2023-06-08 15:53:15,228][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002F3BB6057F0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 15:53:15,231][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002F3BB605970>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 15:53:15,234][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002F3BB605AF0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
