[2023-05-25 10:29:23,281][urllib3.connectionpool][WARNING] - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119EA75A0A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /joe88data/loan-default-prediction-model.mlflow/api/2.0/mlflow/runs/create
[2023-05-25 10:29:27,289][urllib3.connectionpool][WARNING] - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119EA75A1C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /joe88data/loan-default-prediction-model.mlflow/api/2.0/mlflow/runs/create
[2023-05-25 10:29:35,304][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119EA75A100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /joe88data/loan-default-prediction-model.mlflow/api/2.0/mlflow/runs/create
[2023-05-25 10:29:53,486][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119EA75A850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /joe88data/loan-default-prediction-model.mlflow/api/2.0/mlflow/runs/create
[2023-05-25 10:30:25,548][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119EA75A6D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /joe88data/loan-default-prediction-model.mlflow/api/2.0/mlflow/runs/create
