[2023-06-08 14:05:44,763][whylogs.api.usage_stats][WARNING] - Connection error. Skip stats collection.
[2023-06-08 14:08:25,680][whylogs.api.writer.whylabs][INFO] - checking: https://whylabs-public.s3.us-west-2.amazonaws.com/whylogs_config/whylabs_condition_count_disabled
[2023-06-08 14:08:25,735][whylogs.api.writer.whylabs][WARNING] - Error trying to read whylabs config, falling back to defaults for uncompounding
[2023-06-08 14:08:25,822][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DCBC6448B0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 14:08:25,823][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DCBC644A30>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 14:08:25,826][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DCBC644BB0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
