[2023-06-09 00:52:57,843][whylogs.api.usage_stats][WARNING] - Connection error. Skip stats collection.
[2023-06-09 00:55:31,717][whylogs.api.writer.whylabs][INFO] - checking: https://whylabs-public.s3.us-west-2.amazonaws.com/whylogs_config/whylabs_condition_count_disabled
[2023-06-09 00:55:31,722][whylogs.api.writer.whylabs][WARNING] - Error trying to read whylabs config, falling back to defaults for uncompounding
[2023-06-09 00:55:31,767][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020296CE26D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-09 00:55:31,769][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020296CE2850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-09 00:55:31,770][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020296CE29D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
